# Generated by Django 4.2.15 on 2024-09-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('classics', 'Classics'), ('historical', 'Historical'), ('mystery_thriller', 'Mystery & Thriller'), ('scifi_fantasy', 'Science Fiction & Fantasy'), ('biography', 'Biography & Memoir'), ('other', 'Other')], default='other', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
