# Generated by Django 4.2.15 on 2024-09-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, help_text='13 Character ISBN number', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
