# Generated by Django 4.2.15 on 2024-09-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
